balances

diff --git a/gg b/gg
--- a/gg
+++ b/gg
@@ -135,6 +135,10 @@ __main() {
       shift
       handle_price_cmd "$@"
       ;;
+    bal:*)
+      shift
+      handle_bal_cmd "$@"
+      ;;
 #    reveal:*)
 #      shift
 #      handle_reveal_cmd "$@"
@@ -156,6 +160,9 @@ __main() {
 "
       COMMAND="price"
       cmdl="$cmdl$( command_usage_line Number of GG received per 1 GULD burn contract. )
+"
+      COMMAND="bal"
+      cmdl="$cmdl$( command_usage_line [user] gg group balance for [user] or whole group. )
 "
 #       COMMAND="reveal"
 #       cmdl="$cmdl$( command_usage_line Reveal answer and end the game. )
@@ -402,6 +409,58 @@ handle_reveal_cmd() {
 
 # $1 is now sub-command
 # $@ are params for the sub-command
+handle_stake_cmd() {
+  pulled=$( git pull origin master 2>&1 )
+
+  if [ "$1" != "" ] ; then
+    GINSTANCE=$1
+    if ! [ -d "LOTTERY/$GINSTANCE" ] ; then
+      echo "Game $GINSTANCE does not exist. Pick an open game."
+      exit
+    else
+      cd "LOTTERY/$GINSTANCE"
+    fi
+  else
+    cmdl="$( subcommand_usage_line stake <game> Stake maximum amount allowable per game. )
+"
+    echo "$USAGE_PREAMBLE$cmdl$GENERAL_USAGE$USAGE_SUFFIX"
+    exit
+  fi
+
+  BET=$( cat BET.txt )
+  DEALER=$( cat DEALER.txt )
+  PLAYER=$( cat PLAYER.txt )
+  GUESS=$( cat guess )
+  SECRET=$( cat SECRET.txt )
+  ANSWER=$( printf "%s:%s:%s" "$GINSTANCE" "$MAX" "$SECRET" )
+  if [ "$GUESS" = "" ] ; then
+    echo "invalid guess"
+    exit
+  elif [ "$GUESS" = "$ANSWER" ] ; then
+    echo "You lost."
+    WINNER=$PLAYER
+  else
+    echo "You won!"
+    WINNER=$DEALER
+  fi
+
+  EPOCH_TIME=$( date -u +%s )
+  TDATE=$( date -u +%Y/%m/%d )
+  CLAIM=$"$TDATE * GG LOTTERY $GINSTANCE CLAIM
+    ; timestamp: $EPOCH_TIME
+    gg:Games:LOTTERY:$GINSTANCE    -$WINNINGS GG
+    gg:Games:LOTTERY:$GINSTANCE:$WINNER    $WINNINGS GG"
+  echo "$CLAIM"
+  echo "$CLAIM" > "$EPOCH_TIME.dat"
+  pulled=$( git add "$EPOCH_TIME.dat" 2>&1 )
+
+  pulled=$( git add SECRET.txt signum.asc guess 2>&1 )
+  pulled=$( git commit -m "reveal" 2>&1 )
+  pulled=$( git push origin master 2>&1 )
+}
+
+# $1 is now sub-command
+# $@ are params for the sub-command
 handle_price_cmd() {
   year=$( date -u +%Y )
   month=$( date -u +%m )
@@ -422,6 +481,31 @@ handle_price_cmd() {
     fi
   done < "$PRICE_DIR/gg.db"
   echo $price
+}
+
+# $1 is now sub-command
+# $@ are params for the sub-command
+handle_bal_cmd() {
+  if [ "$1" == "" ] ; then
+    usearch=".*"
+  else
+    usearch=":$1"
+  fi
+  eqtx=$( find ~/ledger -name '*.d*' | grep "\.d[bat]*$" | while read line ; do echo include $line ; done | ledger -f - equity ^.*:gg$usearch ^gg:.*$usearch )
+  # printf "%s\n" "$eqtx"
+  if [ ! "$1" == "" ] ; then
+    GG_TOTAL_INV=$( printf "%s" "$eqtx" | grep "^ *Equity:Opening Balances.*GG$" | grep -o [0-9\.\,-]* )
+    GG_TOTAL_INV=$( echo "${GG_TOTAL_INV/,/}" )
+    GG_TOTAL=$( bc <<< "scale=8; $GG_TOTAL_INV*-1" )
+    GULD_TOTAL=$( printf "%s" "$eqtx" | grep "^ *Equity:Opening Balances.*GULD$" | grep -o [0-9\.\,-]* )
+  else
+    GG_TOTAL=0
+    GULD_TOTAL=$( printf "%s" "$eqtx" | grep "^ *Equity:Opening Balances.*GULD$" | grep -o [0-9\.\,-]* )
+  fi
+  ggaccounts=$( printf "%s" "$eqtx" | grep gg:[EG][qa] )
+  guldaccounts=$( printf "%s" "$eqtx" | grep :gg: )
+  printf "%s\n%s\n---------------\n" "$ggaccounts" "$guldaccounts"
+  printf "%s GG\n%s GULD\n" "$GG_TOTAL" "$GULD_TOTAL"
 }
 
 #-------------------user prep and command section--------------------------
