balance limits

diff --git a/gg b/gg
--- a/gg
+++ b/gg
@@ -63,6 +63,9 @@ if [ $MYOS != "Linux" ] && [ $MYOS != "Darwin" ] ; then
   exit 1
 fi
 
+EPOCH_TIME=$( date -u +%s )
+TDATE=$( date -u +%Y/%m/%d )
+
 #------------------------CLI Helpers--------------------------
 USAGE_PREAMBLE="
   $PROG_NAME  Play guld games
@@ -224,7 +227,6 @@ handle_new_cmd() {
       GULDBET=$( printf "%.8f\n" $GULDBETF | bc | sed 's/^\./0./' )
     fi
   fi
-  EPOCH_TIME=$( date -u +%s )
   if [ $MYOS = "Linux" ] ; then
     SECRET=$( shuf -i 0-$MAX -n 1 )
   elif [ $MYOS = "Darwin" ] ; then
@@ -314,7 +316,6 @@ handle_guess_cmd() {
     GULDBET=$( printf "%.8f\n" "$GULDBETF" | bc | sed 's/^\./0./' )
   fi
   pulled=$( git add PLAYER.txt 2>&1 )
-  EPOCH_TIME=$( date -u +%s )
   FUNDING=$( get_game_funding $USER_NAME $GINSTANCE $BET )
   echo "$FUNDING"
   siguess=$(printf "%s:%s:%s" "$GINSTANCE" "$MAX" "$GUESS" | gpg2 -u $USER_SIGNINGKEY --clearsign  2>/dev/null )
@@ -391,8 +392,6 @@ handle_reveal_cmd() {
     WINNER=$DEALER
   fi
 
-  EPOCH_TIME=$( date -u +%s )
-  TDATE=$( date -u +%Y/%m/%d )
   CLAIM=$"$TDATE * GG LOTTERY $GINSTANCE CLAIM
     ; timestamp: $EPOCH_TIME
     gg:Games:LOTTERY:$GINSTANCE    -$WINNINGS GG
@@ -460,8 +459,6 @@ handle_stake_cmd() {
     exit
   fi
 
-  EPOCH_TIME=$( date -u +%s )
-  TDATE=$( date -u +%Y/%m/%d )
   STAKE=$"$TDATE * GG LOTTERY $GINSTANCE STAKE
     ; timestamp: $EPOCH_TIME
     gg:Games:LOTTERY:$GINSTANCE:$WINNER    -$BET GG
@@ -574,12 +571,15 @@ get_game_funding() {
           ggbal=$( echo $bal | grep -o "[0-9.,]*" | sed 's/,//' )
         fi
       else
-        echo "unknown balance format"
+        $( >&2 echo "unknown balance format" )
         exit 1
       fi
     elif [ "$bal" = "---------------" ] ; then
       intotals=1
     else
+      if [ "$bal" == "" ] ; then
+        continue
+      fi
       if [[ $bal =~ $gg:Equity ]] ; then
         if [ "$MYOS" = "Darwin" ] ; then
           ggequity=$( echo $bal | ggrep -o "[0-9.,]*" | sed 's/,//' )
@@ -599,12 +599,18 @@ get_game_funding() {
     fi
   done <<< "$bals"
 
-  EPOCH_TIME=$( date -u +%s )
-  TDATE=$( date -u +%Y/%m/%d )
   FUNDING=$"$TDATE * GG LOTTERY $2 FUNDING
     ; timestamp: $EPOCH_TIME"
 
   bet=$3
+  total=$( echo "$guldggval+$ggbal" | bc | sed 's/^\./0./' )
+  sufficent=$( echo "$total>=$bet" | bc )
+
+  if [ "$sufficent" != "1" ] ; then
+    $( >&2 echo "ERROR: insufficient funds" )
+    $( >&2 echo "Max bet: $total" )
+    exit 1
+  fi
   if [ $( echo "$guldggval>0" | bc ) = "1" ] ; then
     if [ $( echo "$guldggval>=$bet" | bc ) = "1" ] ; then
       amt=$bet
@@ -628,7 +634,9 @@ get_game_funding() {
   newbet=$( echo "$bet==0" | bc )
   if [ "$newbet" = "1" ] ; then
     printf "%s\n" "$FUNDING"
+    return
   else
+    i=$(( $i - 1 ))
     for ii in $( seq 0 $i ) ; do
       testbc=$( echo "${subals[$ii]}>=$bet" | bc )
       if [ "$testbc" = "1" ] ; then
@@ -643,9 +651,22 @@ get_game_funding() {
       newbbet=$( echo "$bet==0" | bc )
       if [ "$newbbet" = "1" ] ; then
         printf "%s\n" "$FUNDING"
-        break
+        return
       fi
     done
+  fi
+  newbet=$( echo "$bet==0" | bc )
+  if [ "$newbet" = "1" ] ; then
+    printf "%s\n" "$FUNDING"
+    return
+  else
+    if [ testbc=$( echo "$ggequity>=$bet" | bc ) ] ; then
+      FUNDING=$"$FUNDING
+    gg:Equity:$1    -$bet GG
+    gg:Games:LOTTERY:$2    $bet GG"
+    printf "%s\n" "$FUNDING"
+    return
+    fi
   fi
 }
 
